apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ${JOB_NAME}
  name: ${JOB_NAME}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${JOB_NAME}
  template:
    metadata:
      creationTimestamp: null
      labels:
        build_number: ${BUILD_NUMBER}
        app: ${JOB_NAME}
    spec:
      containers:
      - image: ${JOB_NAME}:latest
        imagePullPolicy: IfNotPresent
        name: ${JOB_NAME}
        ports:
        - containerPort: 8080
