apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ${JOB_NAME}
  name: ${JOB_NAME}
spec:
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30080
    targetPort: 8080
  selector:
    app: ${JOB_NAME}
  type: NodePort
status:
  loadBalancer: {}
