apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyflask
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Arboulahdour/pyflask.git
    targetRevision: v0.1.0
    path: helm/pyflask
    helm:
      valueFiles:
        - ./values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pyflask-staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true