apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pyflask
  name: pyflask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pyflask
  template:
    metadata:
      labels:
        app: pyflask
    spec:
      containers:
      - image: arboulahdour/pyflask:1.0.0
        name: pyflask
        ports:
        - containerPort: 5000
