name: CI Pipeline For a Flask App
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    #if: startsWith(github.ref, 'refs/tags/')
    steps:
      -
        name: Checkout ${GITHUB_REF#refs/heads/}
        uses: actions/checkout@v3
      -
        name: echo '${GITHUB_REF#refs/heads/}'
        run: echo '${GITHUB_REF#refs/heads/}'
      -
        name: echo "${GITHUB_REF#refs/heads/}"
        run: echo "${GITHUB_REF#refs/heads/}"
